/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas_InternasAdmin;

import controlador.c_ingresoAlmacen;

/**
 *
 * @author LUIS
 */
public class vi_ingresoAlmacen extends javax.swing.JInternalFrame {

    c_ingresoAlmacen c;
    public vi_ingresoAlmacen() {
        initComponents();
        c =new c_ingresoAlmacen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        txtIdproducto = new javax.swing.JTextField();
        txtcantidadIngresada = new javax.swing.JTextField();
        txt_precioCompra = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txRUC = new javax.swing.JTextField();
        boton_cargarCodigo_producto = new javax.swing.JButton();
        boton_registrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LBLidEmpleado = new javax.swing.JLabel();
        boton_buscar_proveedor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadTotal = new javax.swing.JLabel();
        boton_añadir = new javax.swing.JButton();
        txtnombrePro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        boton_mostrar_todo = new javax.swing.JButton();
        boton_actualisar = new javax.swing.JButton();
        boton_filtrar = new javax.swing.JButton();
        boton_cargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("INGRESO ALMACEN");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre Pro :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, -1, -1));

        jLabel4.setText("Idproducto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 68, -1, -1));

        jLabel5.setText("Cantidad :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 163, -1, -1));

        jLabel6.setText("Precio compra :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 188, -1, -1));

        jLabel7.setText("Precio Venta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 219, -1, -1));
        jPanel1.add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 166, -1));
        jPanel1.add(txtIdproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 78, -1));
        jPanel1.add(txtcantidadIngresada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 166, -1));
        jPanel1.add(txt_precioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 166, -1));
        jPanel1.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 166, -1));

        jLabel10.setText("Proveedor :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 9, -1, -1));
        jPanel1.add(txRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 122, -1));

        boton_cargarCodigo_producto.setText("B");
        jPanel1.add(boton_cargarCodigo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 53, -1));

        boton_registrar.setText("Registrar Pro");
        jPanel1.add(boton_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, -1));

        jLabel1.setText("IdEmpleado :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 459, -1, -1));

        LBLidEmpleado.setText(".....");
        jPanel1.add(LBLidEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 459, -1, -1));

        boton_buscar_proveedor.setText("jButton1");
        jPanel1.add(boton_buscar_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 38, -1));

        jLabel2.setText("Total :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 459, -1, -1));

        txtCantidadTotal.setText(".......");
        jPanel1.add(txtCantidadTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 459, -1, -1));

        boton_añadir.setText("+");
        jPanel1.add(boton_añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));
        jPanel1.add(txtnombrePro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 166, -1));

        jLabel9.setText("Nombre pro:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 96, -1, -1));

        jLabel11.setText("Cantidad :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 127, -1, -1));

        jPanel1.add(cbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 166, -1));

        boton_mostrar_todo.setText("Mostrar Todo");
        jPanel1.add(boton_mostrar_todo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, -1));

        boton_actualisar.setText("Actualizar");
        jPanel1.add(boton_actualisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, -1));

        boton_filtrar.setText("Filtrar menor");
        jPanel1.add(boton_filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        boton_cargar.setText("Cargar");
        jPanel1.add(boton_cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LBLidEmpleado;
    public javax.swing.JButton boton_actualisar;
    public javax.swing.JButton boton_añadir;
    public javax.swing.JButton boton_buscar_proveedor;
    public javax.swing.JButton boton_cargar;
    public javax.swing.JButton boton_cargarCodigo_producto;
    public javax.swing.JButton boton_filtrar;
    public javax.swing.JButton boton_mostrar_todo;
    public javax.swing.JButton boton_registrar;
    public javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txRUC;
    public javax.swing.JLabel txtCantidadTotal;
    public javax.swing.JTextField txtIdproducto;
    public javax.swing.JTextField txtPrecioVenta;
    public javax.swing.JTextField txt_precioCompra;
    public javax.swing.JTextField txtcantidadIngresada;
    public javax.swing.JTextField txtdescripcion;
    public javax.swing.JTextField txtnombrePro;
    // End of variables declaration//GEN-END:variables
}
